# fly.toml app configuration file generated for admin-server-drophouse on 2024-07-09T00:53:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backbone-drophouse'
primary_region = 'ewr'
[env]
PORT = "8080"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1