# name: Fly Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2
#         uses: superfly/flyctl-actions/setup-flyctl@master
#         run:  flyctl deploy --remote-only

   